### ISSUE TITLE
NaCl/PNaCl-based extension

### ISSUE THREAD

**Issue by tofutim** [ligershark/ChromeExtensionProjectTemplate#2]
Very nice. Could this be used also to make NaCl/PNaCl-based extensions?  https://developers.google.com/native-client/dev/sdk/download

**Comment by ccslabs** [comment]
Wouldn't you use a contentscript.js and insert the embed information for the NaCl into the page?

**Comment by madskristensen** [comment]
I don't follow. Is this an issue with the code in this repo?

**Comment by ccslabs** [comment]
@madskristensen 
No it was in reply to tofutim - not sure how to male the bridge. Sorry I should have been more clearer.
